[configuration]
# Directory to output the JSON files to
output_directory = "build"
# Maximum number of points per aircraft before an error is emitted
max_points = 100

[aircraft]
A320 = { f = "source/airbus/a320.svg", attr = "VATSIM-Radar", l = 123.25, w = 111.833, optimizer = { t = "ad_floor", a_floor = 0.15, d_floor = 0.2 }} # Nose-to-tail 123 ft 3 in, wingspan 11 ft 10 in
A320_AV = { f = "source/airbus/a320.svg", attr = "VATSIM-Radar", l = 123.25, w = 111.833, optimizer = { t = "3pt_avg", dt = 0.3 }}