name: Build

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always


jobs:
  build:
    name: Build aircraft files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Build generator tool
        run: cargo build --verbose

      - name: Generate aircraft
        run: cargo run -- -c config.toml build

      - name: Upload aircraft specs
        uses: actions/upload-artifact@v2
        with:
          name: aircraft_specs
          path: build